type: yolov8_seg
name: yolov8l-seg-r20230620
display_name: YOLOv8l-Seg Ultralytics
model_path: https://github.com/CVHub520/X-AnyLabeling/releases/download/v0.1.0/yolov8l-seg.onnx
nms_threshold: 0.45
confidence_threshold: 0.25
classes:
  - wire
